version: '3.5'

services:
    celery_demo:
        image: sample/celery_demo
        environment:
            - APP_ENVIRONMENT=staging
            - SECRET_KEY_VALUE=bDf%Ma*y8HX6S2zZVMP37bbWc^zLT#jwDTFMP7hZFZvWczeD5@
            - DEBUG_VALUE=true
            - ALLOWED_HOSTS_VALUE=*
            - DATABASE_NAME_VALUE=celery-demo
            - DATABASE_USER_VALUE=postgres-admin
            - DATABASE_PASSWORD_VALUE=j*B&72_#AX_wj8*MgY=j!4u=^b?M*Mwtu@%K
            - DATABASE_HOSTNAME_VALUE=db
            - DATABASE_PORT_VALUE=5432
            - CELERY_BROKER_URL_VALUE=amqp://celerydemo:celerydemo@192.168.33.30//
            - CELERY_ACCEPT_CONTENT_VALUE=json;
            - CELERY_RESULT_BACKEND_VALUE=db+sqlite:///results.sqlite
            - CELERY_TASK_SERIALIZER_VALUE=json
        entrypoint: /app/tools/docker/migration_entrypoint.sh
        networks:
            - internal_db

networks:
    internal_db:
